# -*- coding: utf-8 -*-
"""Bayesian Marketing Mix Modeling (MMM) using PyMC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vm1zfPkApu4_HZguwt99M405rJeF-nac
"""

# Objective : Develop a Bayesian Marketing Mix Model using PyMC to quantify the impact of different marketing channels on sales while accounting for carryover (adstock) and diminishing returns (saturation).
# Use the model outputs to estimate channel-wise contribution and ROI, enabling data-driven budget allocation and optimization decisions.

"""**Load Data and Preprocessing**


"""

# Load Data

import pandas as pd
df = pd.read_csv('/content/Conjura_Data.csv')
df.head()

# Convert date

pd.to_datetime(df['WEEK'])

# Set Target Variable
y = df['Value'].values

# Set Media Varibles
media_cols = [
    'GOOGLE_PAID_SEARCH_IMPRESSIONS',
    'GOOGLE_SHOPPING_IMPRESSIONS',
    'GOOGLE_PMAX_IMPRESSIONS',
    'GOOGLE_DISPLAY_IMPRESSIONS',
    'GOOGLE_VIDEO_IMPRESSIONS',
    'META_FACEBOOK_IMPRESSIONS',
    'META_INSTAGRAM_IMPRESSIONS',
    'META_OTHER_IMPRESSIONS',
    'TIKTOK_IMPRESSIONS']

X_media = df[media_cols].values

# Set Control Variables

control_cols = [
    'Avg Price',
    'Discount',   # promo variable
    'DIRECT_CLICKS',
    'BRANDED_SEARCH_CLICKS',
    'ORGANIC_SEARCH_CLICKS',
    'EMAIL_CLICKS',
    'REFERRAL_CLICKS',
    'ALL_OTHER_CLICKS']

X_ctrl = df[control_cols].values

# Scale variables

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_media_scaled = scaler.fit_transform(X_media)
X_ctrl_scaled = scaler.fit_transform(X_ctrl)
y_scaled = scaler.fit_transform(y.reshape(-1, 1)) .flatten()   # reshape y from 1D (n,) to 2D (n,1) as StandardScaler expects 2D input


print("y_scaled:", y_scaled.shape)
print("X_media_sat:", X_media_scaled.shape)
print("X_ctrl_scaled:", X_ctrl_scaled.shape)

"""**Adstock Transformation**"""

# define adstock

import numpy as np

def adstock(x, theta):              # Adstock_t = x_t + θ * Adstock_{t-1}
    result = np.zeros_like(x)
    result[0] = x[0]

    for t in range(1, len(x)):
        result[t] = x[t] + theta * result[t-1]

    return result

# applying adstock to media

theta = 0.5  # initial assumption

X_media_ads = np.zeros_like(X_media_scaled)

for i in range(X_media_scaled.shape[1]):
    X_media_ads[:, i] = adstock(X_media_scaled[:, i], theta)

# check shape

X_media_ads.shape == X_media_scaled.shape

"""**Saturation Modeling**"""

# implement hill function
# f(x) = x^α / (x^α + γ^α)
# <1 : slow growth
# =1 : moderate growth
# >1 : S-Shaped curve


def hill_function(x, alpha=1.5, gamma=1):
    x = np.maximum(x, 0)   #  Remove negative values
    return (x**alpha) / (x**alpha + gamma**alpha + 1e-6)


# apply saturation on adstocked media

X_media_sat = hill_function(X_media_ads)

# Visual check

import matplotlib.pyplot as plt

plt.figure(figsize=(6,3))

plt.plot(X_media_ads[:,0], label='Adstock')
plt.plot(X_media_sat[:,0], label='Saturated')

plt.legend()
plt.title(media_cols[0])
plt.show()

"""***PyMC Model Specification (Bayesian MMM)***"""

import pymc as pm
import numpy as np

# ✅ Ensure everything is numpy
X_media_sat = np.array(X_media_sat)
X_ctrl_scaled = np.array(X_ctrl_scaled)
y_scaled = np.array(y_scaled).flatten()

# ✅ Define dimensions
n_media = X_media_sat.shape[1]
n_ctrl = X_ctrl_scaled.shape[1]

# ✅ Build model
with pm.Model() as mmm:

    # Intercept (baseline sales)
    intercept = pm.Normal("intercept", mu=0, sigma=1)

    # Media coefficients (positive constraint)
    beta_media = pm.HalfNormal("beta_media", sigma=1, shape=n_media)

    # Control coefficients (can be positive or negative)
    beta_ctrl = pm.Normal("beta_ctrl", mu=0, sigma=1, shape=n_ctrl)

    # Noise
    sigma = pm.HalfNormal("sigma", sigma=1)

    mu = (
        intercept
        + pm.math.sum(X_media_sat * beta_media, axis=1)
        + pm.math.sum(X_ctrl_scaled * beta_ctrl, axis=1)
    )

    # 🔹 Likelihood
    y_obs = pm.Normal("y_obs", mu=mu, sigma=sigma, observed=y_scaled)

"""**Sampling**

"""

# Sampling : Drawing from posterior distributions
# In classical Regression: You get ONE value for each coefficient (β)
# In Bayesian : You get a DISTRIBUTION of values for each β

# What happens internally?
# NUTS (No-U-Turn Sampler)
# A form of Hamiltonian Monte Carlo

# Starts with random parameters
# Generates predictions
# Compares with actual data
# Adjusts parameters
# Repeats thousands of times

#  draws=2000: Final posterior samples per chain = 2000
#  tune=2000 : Warm-up phase (NOT used in final results)
#  Runs 4 independent processes
# how cautious the sampler is ( 0.8 : Faster but risky, 0.9: Stable, 0.95: slower and safer)

with mmm:
    trace = pm.sample(
        draws=2000,
        tune=2000,
        chains=4,
        target_accept=0.9,
        random_seed=42,
        progressbar=True,    # hows live progress
        cores=4              # parallel execution
    )

"""**Model Diagnostics**"""

# R-hat (convergence metric): r_hat ≈ 1.00 GOOD (To evaluate whether an algorithm has successfully converged)
# ESS (Effective Sample Size): > 200 good, > 500 very good
# Mean values (sanity check) :

import arviz as az
az.summary(trace)

# trace plots
az.plot_trace(trace, var_names=["intercept", "beta_media", "beta_ctrl"])

"""# **Contribution Calculation**"""

# Extract posterior means
beta_media_mean = trace.posterior['beta_media'].mean(dim=('chain','draw')).values

# Compute contributions
media_contribution = X_media_sat * beta_media_mean

contribution_df = pd.DataFrame(media_contribution, columns=media_cols)

# Total contribution per channel
channel_contribution = contribution_df.sum().sort_values(ascending=False)
print(channel_contribution)

"""**Model Validation**"""

# Train test split

split_idx = int(0.8 * len(df))

# Train
X_media_train = X_media_sat[:split_idx]
X_ctrl_train = X_ctrl_scaled[:split_idx]
y_train = y_scaled[:split_idx]

# Test
X_media_test = X_media_sat[split_idx:]
X_ctrl_test = X_ctrl_scaled[split_idx:]
y_test = y_scaled[split_idx:]

# Rebuild model on train data

with pm.Model() as mmm_train:

    intercept = pm.Normal("intercept", mu=0, sigma=1)

    beta_media = pm.HalfNormal("beta_media", sigma=1, shape=n_media)
    beta_ctrl = pm.Normal("beta_ctrl", mu=0, sigma=1, shape=n_ctrl)

    sigma = pm.HalfNormal("sigma", sigma=1)

    mu = (
        intercept
        + pm.math.sum(X_media_train * beta_media, axis=1)
        + pm.math.sum(X_ctrl_train * beta_ctrl, axis=1)
    )

    y_obs = pm.Normal("y_obs", mu=mu, sigma=sigma, observed=y_train)

# train model

with mmm_train:
    trace_train = pm.sample(
        draws=1500,
        tune=1500,
        chains=4,
        target_accept=0.9,
        random_seed=42)

# Get posterior means (for prediction)
beta_media_mean = trace_train.posterior['beta_media'].mean(dim=('chain','draw')).values
beta_ctrl_mean = trace_train.posterior['beta_ctrl'].mean(dim=('chain','draw')).values
intercept_mean = trace_train.posterior['intercept'].mean().values

# Predict on TEST data

y_pred_test = (
    intercept_mean
    + np.sum(X_media_test * beta_media_mean, axis=1)
    + np.sum(X_ctrl_test * beta_ctrl_mean, axis=1)
)

"""**Evaluation Metrics**"""

import numpy as np
from sklearn.metrics import r2_score, mean_absolute_percentage_error

# R² (goodness of fit)
r2 = r2_score(y_test, y_pred_test)

# MAPE (%)
mape = mean_absolute_percentage_error(y_test, y_pred_test) * 100

# RMSE
rmse = np.sqrt(np.mean((y_test - y_pred_test) ** 2))

print(f"R²: {r2:.4f}")
print(f"MAPE: {mape:.2f}%")   # less interpretable on scaled data
print(f"RMSE: {rmse:.4f}")

# Durbin Watson

from statsmodels.stats.stattools import durbin_watson

residuals = y_test - y_pred_test

dw = durbin_watson(residuals)

print(f"Durbin-Watson: {dw:.3f}")

"""**Actual VS Predicted**"""

import matplotlib.pyplot as plt

plt.figure(figsize=(6,3))

plt.plot(y_test, label="Actual (Scaled)", linewidth=2)
plt.plot(y_pred_test, label="Predicted (Scaled)", linestyle="--")

plt.title("Actual vs Predicted (Scaled)")
plt.xlabel("Time Index")
plt.ylabel("Scaled Value")

plt.legend()
plt.grid(True)

plt.show()

"""**Deliverables Calculations**"""

# Convert scaled contribution to real value

y_std = y.std()

media_contribution_real = media_contribution * y_std

# Convert to DataFrame
contribution_df_real = pd.DataFrame(
    media_contribution_real,
    columns=media_cols
)

# Incremental value
incremental_value = contribution_df_real.sum()

print("Incremental Value (by channel):\n")
print(incremental_value.sort_values(ascending=False))


# Effectiveness
effectiveness = incremental_value / incremental_value.sum()

print("Effectiveness (% contribution):\n")
print(effectiveness.sort_values(ascending=False))

print("\nTotal Effectiveness:", effectiveness.sum())

"""**Response curves**"""

def response_curve(x, beta, alpha=1.5, gamma=1):
    x = np.maximum(x, 0)
    return beta * (x**alpha / (x**alpha + gamma**alpha + 1e-6))

import numpy as np
import matplotlib.pyplot as plt

# Pick channel
channel = 'META_FACEBOOK_IMPRESSIONS'
idx = media_cols.index(channel)

# Range of input (simulate more spend)
x_range = np.linspace(
    X_media_ads[:, idx].min(),
    X_media_ads[:, idx].max() * 2,
    100
)

# Generate response
beta = beta_media_mean[idx]
response = response_curve(x_range, beta)

# Plot MULTIPLE channels
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))

for i, col in enumerate(media_cols):
    beta = beta_media_mean[i]

    x_range = np.linspace(
        X_media_ads[:, i].min(),
        X_media_ads[:, i].max() * 2,
        100
    )

    response = response_curve(x_range, beta)

    plt.plot(x_range, response, label=col)

plt.legend()
plt.title("Response Curves (All Channels)")
plt.xlabel("Impressions")
plt.ylabel("Contribution (scaled)")
plt.grid(True)

plt.show()

# Marginal Curve
marginal = np.gradient(response, x_range)

plt.figure(figsize=(6,4))
plt.plot(x_range, marginal)

plt.title(f"Marginal Response: {channel}")
plt.xlabel("Impressions")
plt.ylabel("Marginal Contribution")
plt.grid(True)

plt.show()



"""**52-WEEK FORECAST**"""